### ISSUE TITLE
Boost mode functionality redesign

### ISSUE THREAD

**Issue by gulliverrr** [HestiaPi/hestia-touch-openhab#23]
For houses where heating is on AUTO most of the time, Boost makes no sense as it is now.
Boost should probably ignore the setpoint and simply run for the selected time.
Boost should work for all functions in the same way (heating, cooling, fan, humidity).

**Comment by rkoshak** [comment]
The fix for this should wait until #26 get's checked in and merged. Once done the fix is really simple and I've already added a TODO comment explaining what and where the changes need to be made.  

Essentially, the now merged Boost mode rule needs to call a different lambda instead of the one it currently calls and the lambdas for heating and humidity need to check if we are currently in Boost mode and if so ignore changes in the sensor readings and just keep the device on for the Boost time.
