### ISSUE TITLE
 Does Auto need to be available to the user for Fan?

### ISSUE THREAD

**Issue by gulliverrr** [HestiaPi/hestia-touch-openhab#9]
Resolved for Touch UI.
https://github.com/HestiaPi/hestia-touch-one-ui/issues/9
Needs to be addressed in OH UI too.

**Comment by rkoshak** [comment]
I'm not sure I understand what needs to be done to the OH UI. Just remove the "AUTO" Option from the Fan?

Based on what I did with PR #34, I think I can go one better. Instead of needing the new FanCtrl Item to control visibility, I can just use the FanMode==AUTO. When the Mode is AUTO, it shows the Text element that just shows the FanPin's state. When not in AUTO, show the ON/OFF buttons.

I'll update PR #34 once I get the answers here for what is intended.
